config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root   'static_pages#backend'
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get    '/static_pages/frontend'

  get    '/signup', to: 'users#new'
  post   '/signup', to: 'users#create'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  namespace :api, defaults: { format: 'json' } do
    resources :money, only: :index
    get '/insert_money', to: 'money#insert'
    get '/take_money', to: 'money#take'
  end

  match '*path' => 'static_pages#index', via: [:get]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    render 'frontend', layout: 'ng_book'
  end

  def frontend
    render layout: 'ng_book'
  end

  def backend
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/backend.html.erb
<% if logged_in? %>
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <%= render 'shared/user_info' %>
        </section>
        <section class="stats">
          <%= render 'shared/stats' %>
        </section>
        <section class="micropost_form">
          <%= render 'shared/micropost_form' %>
        </section>
      </aside>
      <div class="col-md-8">
        <h3>Micropost Feed</h3>
        <%= render 'shared/feed' %>
      </div>
    </div>
<% else %>
  <p>
    <%= link_to 'Frontend', static_pages_frontend_path, target: '_blank', class: 'btn btn-lg btn-primary' %>
  </p>
  <p>
    <%= link_to 'Sign up', signup_path, class: 'btn btn-lg btn-primary' %>
  </p>
<% end %>

app/views/static_pages/frontend.html.erb
<nefor-project>Creating...</nefor-project>

<%= javascript_pack_tag 'nefor' %>

app/views/static_pages/index.html.erb
<nefor-project>Creating...</nefor-project>

<%= javascript_pack_tag 'nefor' %>